#!/usr/bin/env ruby

require 'rubygems'
require 'singleton'
require 'net/pop'
require 'mail'
require 'github_api'
require 'usb'
require "rexml/document"
require 'open-uri'
require 'net/http'
require "net/https"
require 'yaml'
require 'forwardable'

PROJECT_ROOT = File.expand_path(File.dirname(__FILE__))

require PROJECT_ROOT + '/lib/his_masters_voice'
require PROJECT_ROOT + '/lib/timer'
require PROJECT_ROOT + '/lib/openssl_patch'
require PROJECT_ROOT + '/lib/monitor'
require PROJECT_ROOT + '/lib/gmail/monitor'
require PROJECT_ROOT + '/lib/github/monitor'
require PROJECT_ROOT + '/lib/jenkins/monitor'
require PROJECT_ROOT + '/lib/light/controller'
require PROJECT_ROOT + '/lib/jenkins/status'
require PROJECT_ROOT + '/lib/jenkins/activity'
require PROJECT_ROOT + '/lib/manager'

@manager = Manager.new
# just speaking for the user here i.e. we want the software to behave as if the
# the user asked this
HisMastersVoice.instance.said_this('whats up')

while true != false
  # this makes all registered timers work
  # a cheap copy of ios timer behaviour
  Timer.tick
  @manager.light_the_way
end